export const demoLeads = [
  {
    name: "John Smith",
    email: "john.smith@example.com",
    mobile: "+1-555-0101",
    adults: "2",
    kids: "1",
    persons: "3",
    packageCategory: "Luxury",
    packageType: "Family Package",
    from: "New York",
    destination: "Maldives",
    days: "7",
    nights: "6",
    noOfRooms: "1",
    extraBeds: "0",
    mealPlans: "All Inclusive",
    EP: "Premium",
    travelDate: "2024-07-15",
    source: "Website",
    publish: "Yes",
  },
  {
    name: "Sophie Martinez",
    email: "sophie.m@example.com",
    mobile: "+1-555-0111",
    adults: "2",
    kids: "1",
    persons: "3",
    packageCategory: "Adventure",
    packageType: "Trekking Package",
    from: "Barcelona",
    destination: "Nepal",
    days: "12",
    nights: "11",
    noOfRooms: "1",
    extraBeds: "0",
    mealPlans: "Full Board",
    EP: "Standard",
    travelDate: "2024-09-10",
    source: "Instagram",
    publish: "Yes",
  },
  {
    name: "Thomas Wright",
    email: "thomas.w@example.com",
    mobile: "+1-555-0112",
    adults: "4",
    kids: "0",
    persons: "4",
    packageCategory: "Golf",
    packageType: "Golf Resort Package",
    from: "Edinburgh",
    destination: "Portugal",
    days: "6",
    nights: "5",
    noOfRooms: "2",
    extraBeds: "0",
    mealPlans: "Half Board",
    EP: "Premium",
    travelDate: "2024-10-15",
    source: "Golf Club",
    publish: "Yes",
  },
  {
    name: "Yuki Tanaka",
    email: "yuki.t@example.com",
    mobile: "+1-555-0113",
    adults: "2",
    kids: "2",
    persons: "4",
    packageCategory: "Theme Park",
    packageType: "Disney Package",
    from: "Tokyo",
    destination: "Orlando",
    days: "8",
    nights: "7",
    noOfRooms: "1",
    extraBeds: "1",
    mealPlans: "All Inclusive",
    EP: "Standard",
    travelDate: "2024-11-20",
    source: "Travel Blog",
    publish: "Yes",
  },
  {
    name: "Oliver Thompson",
    email: "oliver.t@example.com",
    mobile: "+1-555-0114",
    adults: "2",
    kids: "0",
    persons: "2",
    packageCategory: "Cruise",
    packageType: "Mediterranean Cruise",
    from: "Rome",
    destination: "Greek Islands",
    days: "10",
    nights: "9",
    noOfRooms: "1",
    extraBeds: "0",
    mealPlans: "Full Board",
    EP: "Premium",
    travelDate: "2024-06-25",
    source: "Cruise Line",
    publish: "No",
  },
  {
    name: "Isabella Silva",
    email: "isabella.s@example.com",
    mobile: "+1-555-0115",
    adults: "1",
    kids: "0",
    persons: "1",
    packageCategory: "Photography",
    packageType: "Photo Tour",
    from: "Rio de Janeiro",
    destination: "Iceland",
    days: "7",
    nights: "6",
    noOfRooms: "1",
    extraBeds: "0",
    mealPlans: "Bed & Breakfast",
    EP: "Premium",
    travelDate: "2024-07-30",
    source: "Photography Club",
    publish: "Yes",
  },
  {
    name: "Hassan Ahmed",
    email: "hassan.a@example.com",
    mobile: "+1-555-0116",
    adults: "3",
    kids: "2",
    persons: "5",
    packageCategory: "Desert Safari",
    packageType: "Desert Adventure",
    from: "Abu Dhabi",
    destination: "Morocco",
    days: "9",
    nights: "8",
    noOfRooms: "2",
    extraBeds: "1",
    mealPlans: "Full Board",
    EP: "Standard",
    travelDate: "2024-08-05",
    source: "Direct",
    publish: "Yes",
  },
  {
    name: "Nina Patel",
    email: "nina.p@example.com",
    mobile: "+1-555-0117",
    adults: "6",
    kids: "0",
    persons: "6",
    packageCategory: "Yoga",
    packageType: "Wellness Retreat",
    from: "Mumbai",
    destination: "Rishikesh",
    days: "14",
    nights: "13",
    noOfRooms: "3",
    extraBeds: "0",
    mealPlans: "Vegetarian Full Board",
    EP: "Premium",
    travelDate: "2024-09-15",
    source: "Yoga Studio",
    publish: "Yes",
  },
  {
    name: "Lucas Müller",
    email: "lucas.m@example.com",
    mobile: "+1-555-0118",
    adults: "2",
    kids: "1",
    persons: "3",
    packageCategory: "Ski",
    packageType: "Winter Sports",
    from: "Munich",
    destination: "Swiss Alps",
    days: "7",
    nights: "6",
    noOfRooms: "1",
    extraBeds: "0",
    mealPlans: "Half Board",
    EP: "Premium",
    travelDate: "2024-12-20",
    source: "Ski Resort",
    publish: "Yes",
  },
  {
    name: "Alexandra Cooper",
    email: "alex.c@example.com",
    mobile: "+1-555-0119",
    adults: "4",
    kids: "3",
    persons: "7",
    packageCategory: "Educational",
    packageType: "Historical Tour",
    from: "Boston",
    destination: "Egypt",
    days: "11",
    nights: "10",
    noOfRooms: "2",
    extraBeds: "2",
    mealPlans: "Full Board",
    EP: "Standard",
    travelDate: "2024-10-25",
    source: "University",
    publish: "No",
  },
  {
    name: "Liam O'Connor",
    email: "liam.o@example.com",
    mobile: "+1-555-0120",
    adults: "2",
    kids: "0",
    persons: "2",
    packageCategory: "Food & Wine",
    packageType: "Culinary Tour",
    from: "Dublin",
    destination: "France",
    days: "8",
    nights: "7",
    noOfRooms: "1",
    extraBeds: "0",
    mealPlans: "Gourmet Package",
    EP: "Premium",
    travelDate: "2024-11-05",
    source: "Food Magazine",
    publish: "Yes",
  },
];

export default demoLeads;
