const demoLeads = [
  {
    name: "John Smith",
    email: "john.smith@example.com",
    mobile: "+1-555-0101",
    adults: "2",
    kids: "1",
    persons: "3",
    packageCategory: "Luxury",
    packageType: "Family Package",
    from: "New York",
    destination: "Maldives",
    days: "7",
    nights: "6",
    noOfRooms: "1",
    extraBeds: "0",
    mealPlans: "All Inclusive",
    EP: "Premium",
    travelDate: "2024-07-15",
    source: "Website",
    publish: "Yes"
  },
  {
    name: "Emma Wilson",
    email: "emma.w@example.com",
    mobile: "+1-555-0102",
    adults: "2",
    kids: "0",
    persons: "2",
    packageCategory: "Honeymoon",
    packageType: "Romantic Getaway",
    from: "London",
    destination: "Bali",
    days: "10",
    nights: "9",
    noOfRooms: "1",
    extraBeds: "0",
    mealPlans: "Half Board",
    EP: "Standard",
    travelDate: "2024-08-20",
    source: "Travel Agent",
    publish: "Yes"
  },
  {
    name: "David Chen",
    email: "david.chen@example.com",
    mobile: "+1-555-0103",
    adults: "4",
    kids: "2",
    persons: "6",
    packageCategory: "Group",
    packageType: "Adventure Package",
    from: "Singapore",
    destination: "New Zealand",
    days: "14",
    nights: "13",
    noOfRooms: "2",
    extraBeds: "1",
    mealPlans: "Full Board",
    EP: "Premium",
    travelDate: "2024-09-05",
    source: "Direct",
    publish: "Yes"
  },
  {
    name: "Sarah Johnson",
    email: "sarah.j@example.com",
    mobile: "+1-555-0104",
    adults: "1",
    kids: "0",
    persons: "1",
    packageCategory: "Solo",
    packageType: "Backpacker",
    from: "Sydney",
    destination: "Thailand",
    days: "5",
    nights: "4",
    noOfRooms: "1",
    extraBeds: "0",
    mealPlans: "Bed & Breakfast",
    EP: "Budget",
    travelDate: "2024-06-10",
    source: "Social Media",
    publish: "No"
  },
  {
    name: "Michael Brown",
    email: "michael.b@example.com",
    mobile: "+1-555-0105",
    adults: "2",
    kids: "3",
    persons: "5",
    packageCategory: "Family",
    packageType: "Beach Resort",
    from: "Toronto",
    destination: "Hawaii",
    days: "8",
    nights: "7",
    noOfRooms: "2",
    extraBeds: "1",
    mealPlans: "All Inclusive",
    EP: "Standard",
    travelDate: "2024-07-25",
    source: "Website",
    publish: "Yes"
  },
  {
    name: "Lisa Anderson",
    email: "lisa.a@example.com",
    mobile: "+1-555-0106",
    adults: "6",
    kids: "0",
    persons: "6",
    packageCategory: "Business",
    packageType: "Corporate Retreat",
    from: "Dubai",
    destination: "Switzerland",
    days: "6",
    nights: "5",
    noOfRooms: "3",
    extraBeds: "0",
    mealPlans: "Full Board",
    EP: "Premium",
    travelDate: "2024-08-15",
    source: "Corporate",
    publish: "Yes"
  },
  {
    name: "Robert Taylor",
    email: "robert.t@example.com",
    mobile: "+1-555-0107",
    adults: "2",
    kids: "0",
    persons: "2",
    packageCategory: "Luxury",
    packageType: "Wine Tour",
    from: "Paris",
    destination: "Italy",
    days: "12",
    nights: "11",
    noOfRooms: "1",
    extraBeds: "0",
    mealPlans: "Half Board",
    EP: "Premium",
    travelDate: "2024-09-20",
    source: "Travel Agent",
    publish: "No"
  },
  {
    name: "Maria Garcia",
    email: "maria.g@example.com",
    mobile: "+1-555-0108",
    adults: "3",
    kids: "1",
    persons: "4",
    packageCategory: "Cultural",
    packageType: "Heritage Tour",
    from: "Mexico City",
    destination: "Japan",
    days: "9",
    nights: "8",
    noOfRooms: "2",
    extraBeds: "0",
    mealPlans: "Bed & Breakfast",
    EP: "Standard",
    travelDate: "2024-10-05",
    source: "Website",
    publish: "Yes"
  },
  {
    name: "James Wilson",
    email: "james.w@example.com",
    mobile: "+1-555-0109",
    adults: "2",
    kids: "2",
    persons: "4",
    packageCategory: "Adventure",
    packageType: "Safari Package",
    from: "Cape Town",
    destination: "Kenya",
    days: "7",
    nights: "6",
    noOfRooms: "1",
    extraBeds: "1",
    mealPlans: "Full Board",
    EP: "Premium",
    travelDate: "2024-11-15",
    source: "Direct",
    publish: "Yes"
  },
  {
    name: "Anna Kim",
    email: "anna.k@example.com",
    mobile: "+1-555-0110",
    adults: "2",
    kids: "0",
    persons: "2",
    packageCategory: "Wellness",
    packageType: "Spa Retreat",
    from: "Seoul",
    destination: "Bali",
    days: "5",
    nights: "4",
    noOfRooms: "1",
    extraBeds: "0",
    mealPlans: "All Inclusive",
    EP: "Premium",
    travelDate: "2024-12-01",
    source: "Social Media",
    publish: "Yes"
  }
];

// You can use this data to populate your database or for testing purposes 